export default function handler(req, res) {
   res.status(200).json(
      {
         highlights: [
            {
               title: "ScopeX Labs - Design",
               type: "work",
               location: "ScopeX",
               tags: ["figma", "photoshop", "illustrator", "jira"],
               description: "ScopeX's Design System, featuring all of ScopeX's branding scheme and UI, and resources. (not all work is shown, please contact me for more samples)",
               img: "/img/design/scopex.webp",
               live: "https://www.figma.com/file/ByOKYT5lnO0pEUVsByX02d/Portfolio-Pieces?node-id=1%3A5546&t=nyUGIScWDuZ5mjMw-3"
            },
            {
               title: "Japanese Garden - Magazine",
               type: "education",
               location: "BCIT",
               tags: ["indesign", "photoshop", "illustrator"],
               img: "/img/design/japanese_garden.webp",
               description: "A magazine dedicated to showcasing and teaching about the traditional Japanese gardens. Created using Indesign, with assets being edited using Photoshop.",
               live: "https://drive.google.com/file/d/19H5n0mnofyhvfxZ_YBlxOuUG2APdeQec/view?usp=sharing",
            },
            {
               title: "Animal Crossing - Animation",
               type: "education",
               location: "BCIT",
               tags: ["illustrator", "after effects"],
               img: "/img/design/ac_animation.webp",
               description: "A small motion graphic animation based off the popular franchise Animal Crossing, created by crafting all assets in Illustrator and then animating using After Effects.",
               live: "https://www.youtube.com/watch?v=da6TO6zRZUs",
            },
         ],
         projects: [
            {
               title: "Toyo Sushi - Menu",
               type: "work",
               location: "Toyo Sushi",
               tags: ["figma", "photoshop", "illustrator"],
               img: "/img/design/toyosushi_menu.webp",
               live: "https://www.figma.com/file/ByOKYT5lnO0pEUVsByX02d/Portfolio-Pieces?node-id=0%3A1&t=rMqWMJhj3L6Rd4pO-3",
            },
            {
               title: "Futterowl",
               type: "education",
               location: "BCIT",
               tags: ["photoshop"],
               img: "/img/design/futterowl.webp",
               live: "https://drive.google.com/file/d/1qoPPinRrmddxMgPvXklO4GkXwwqdFGuq/view?usp=share_link",
            },
            {
               title: "Battle Scene - Vector",
               type: "education",
               location: "BCIT",
               tags: ["illustrator"],
               img: "/img/design/battle_vector.webp",
               live: "https://drive.google.com/file/d/1oQW4L3u6WJYIygODLDD8U4I-lHN00PL6/view?usp=share_link",
            },
            {
               title: "Athlete - Painting",
               type: "education",
               location: "BCIT",
               tags: ["photoshop"],
               img: "/img/design/esport_painting.webp",
               live: "https://drive.google.com/file/d/1P9suIg-PM9lkG8wpIV_flEDCgNa2bECA/view?usp=share_link",
            },
            {
               title: "Athlete - Poster",
               type: "education",
               location: "BCIT",
               tags: ["photoshop"],
               img: "/img/design/esports_poster.webp",
               live: "https://drive.google.com/file/d/1kE7qDrLCaJU8aR-hrYOXq2PM0KcZrvuO/view?usp=sharinge",
            },
            {
               title: "Gamecube Controller - Vector",
               type: "education",
               location: "BCIT",
               tags: ["illustrator"],
               img: "/img/design/gamecube_vector.webp",
               live: "https://drive.google.com/file/d/129Djq-oYM48KHovteYukkOJQ_L4UZZhc/view?usp=share_link",
            },
            {
               title: "Shelfie - App",
               type: "education",
               location: "BCIT",
               img: "/img/development/shelfie.webp",
               tags: ["figma", "photoshop", "illustrator"],
               live: "https://www.figma.com/file/ByOKYT5lnO0pEUVsByX02d/Portfolio-Pieces?node-id=1%3A27828&t=rMqWMJhj3L6Rd4pO-3"
            },
            {
               title: "CookOff! - App",
               type: "education",
               location: "BCIT",
               tags: ["figma", "photoshop", "illustrator"],
               img: "/img/design/cookoff.webp",
               live: "https://www.figma.com/file/ByOKYT5lnO0pEUVsByX02d/Portfolio-Pieces?node-id=1%3A32164&t=GRzy1eLJEyoC6CDH-3",
            },
            {
               title: "SingleMingle - App",
               type: "education",
               location: "BCIT",
               tags: ["figma", "photoshop", "illustrator"],
               img: "/img/design/singlemingle.webp",
               live: "https://www.figma.com/file/ByOKYT5lnO0pEUVsByX02d/Portfolio-Pieces?node-id=1%3A29365&t=nyUGIScWDuZ5mjMw-3",
            },
            {
               title: "Salish Airways - Website",
               type: "education",
               location: "BCIT",
               tags: ["figma", "photoshop", "illustrator"],
               img: "/img/design/salish_airways.webp",
               live: "https://www.figma.com/file/ByOKYT5lnO0pEUVsByX02d/Portfolio-Pieces?node-id=1%3A3&t=rMqWMJhj3L6Rd4pO-3",
            },
            {
               title: "Keybuild - Magazine (PDF ver.)",
               type: "education",
               location: "BCIT",
               tags: ["indesign", "photoshop", "illustrator"],
               img: "/img/design/keybuild.webp",
               live: "https://drive.google.com/file/d/1sDow9w5hJYWXAWiHhjYkgA5E9zlmTGt_/view?usp=sharing",
            },
            {
               title: "Portable World - Flyer",
               type: "education",
               location: "BCIT",
               tags: ["figma", "photoshop", "illustrator"],
               img: "/img/design/gameboy_flyer.webp",
               live: "https://drive.google.com/file/d/1jw3KaocdsT2EGtXBKF0B8amkXdxeCGPO/view?usp=sharing",
            },
            {
               title: "The Proms - Swiss Poster",
               type: "education",
               location: "BCIT",
               tags: ["illustrator"],
               img: "/img/design/the_proms.webp",
               live: "https://drive.google.com/file/d/1IZwstIyBfLg6k1uPFi4O-4JZTcDqI3ov/view?usp=sharing",
            },
            {
               title: "Studio - Brochure",
               type: "education",
               location: "BCIT",
               tags: ["illustrator"],
               img: "/img/design/brochure.webp",
               live: "https://drive.google.com/file/d/1qGjuEgdrqDHUjq7Zi7nr3D7uIxMRBZjH/view?usp=sharing",
            },
            {
               title: "Clock Challenge",
               type: "education",
               location: "BCIT",
               tags: ["figma", "illustrator"],
               img: "/img/design/clock_design.webp",
               live: "https://www.figma.com/file/ByOKYT5lnO0pEUVsByX02d/Portfolio-Pieces?node-id=1%3A4&t=rMqWMJhj3L6Rd4pO-3",
            },

         ]
      }
   )
}
