export default function handler(req, res) {
  res.status(200).json({
    highlights: [
      {
        title: "Personalize.ai",
        description:
          "Coldmailing software that mass personalizes introductions to emails by importing your own sheet file, using OpenAI, Google, and Instantly API.",
        type: "education",
        location: "Lighthouse Labs",
        tags: [
          "react",
          "next.js",
          "sass",
          "framer motion",
          "postgresql",
          "prisma",
          "passport",
          "jsonwebtoken",
        ],
        img: "/img/development/personalize-ai.webp",
        details: "https://github.com/takuyadev/personalize-ai",
      },
      {
        title: "Portfolio (2023)",
        description:
          "Updated personal portfolio using Next.js and Styled Components; utilizing the Static Site Generation to vastly increase performance and load time.",
        type: "personal",
        location: "Personal",
        tags: [
          "react",
          "API",
          "javascript ES6",
          "next.js",
          "styled components",
          "framer motion",
        ],
        img: "/img/development/portfolio.webp",
        live: "https://www.takuyaktoyokawa.ca",
        github: "https://github.com/takuyadev/takuyadev-portfolio-2023",
      },
      {
        title: "Battleship",
        description:
          "Battleship clone that allows you to play against a Computer, or against a local player with a leaderboard that keeps track of the best performing player.",
        type: "personal",
        location: "Personal",
        tags: [
          "react",
          "typescript",
          "framer motion",
          "tailwindCSS",
          "jest",
          "node.js",
          "express",
          "mongoDB",
        ],
        img: "/img/development/battleship.webp",
        live: "https://battleship-clone.vercel.app",
        github: "https://github.com/takuyadev/battleship-clone",
      },
    ],
    projects: [
      {
        title: "Visionary Productions",
        img: "/img/development/visionary_prod.webp",
        type: "work",
        location: "Visionary Productions",
        tags: ["wordpress", "elementor"],
        live: "https://visionaryproductionsinc.com/",
      },
      {
        title: "Portfolio (2021)",
        img: "/img/development/portfolio_2021.webp",
        type: "personal",
        location: "Personal",
        tags: ["react", "next.js", "tailwindCSS"],
        live: "https://portfolio.takuyatoyokawa.vercel.app",
        github: "https://github.com/takuyadev/takuyadev-portfolio-2021",
      },
      {
        title: "Srawana Weather App",
        type: "personal",
        location: "Personal",
        tags: ["react", "API", "framer motion", "styled components"],
        img: "/img/development/srawana_weather.webp",
        live: "https://srawana-weather-app.netlify.app/",
        github: "https://github.com/takuyadev/ghibli-movielist-revamp",
      },
      {
        title: "Luck Tester",
        img: "/img/development/luck_tester.webp",
        type: "education",
        location: "BCIT",
        tags: ["html", "css", "javascript ES6"],
        live: "https://takuyadev.github.io/luck-tester-webdev-finals/",
        github: "https://github.com/takuyadev/luck-tester-webdev-finals",
      },
      {
        title: "Video Game Quiz",
        img: "/img/development/game_quiz.webp",
        type: "education",
        location: "Scrimba",
        tags: ["react", "API"],
        live: "https://react-quizzical-scrimba.netlify.app/",
        github: "https://github.com/takuyadev/react-quizzical-scrimba",
      },
      {
        title: "Jungle E-commerce (Ruby on Rails)",
        type: "education",
        location: "Lighthouse Labs",
        tags: ["Javascript ES6", "ruby on rails"],
        img: "/img/development/jungle.webp",
        github: "https://github.com/takuyadev/jungle-ruby-ecommerce",
      },
      {
        title: "Logeee",
        img: "/img/development/logeee.webp",
        type: "education",
        location: "BCIT",
        tags: ["html", "css", "javascript ES6"],
        live: "https://takuyadev.github.io/logeee/",
        github: "https://github.com/takuyadev/logeee",
      },
      {
        title: "Shelfie",
        img: "/img/development/shelfie.webp",
        type: "education",
        location: "BCIT",
        tags: ["react", "next.js", "styled components"],
        live: "https://shelfie-takuyatoyokawa.vercel.app/Homepage",
        github: "https://github.com/takuyadev/shelfie",
      },
      {
        title: "Minimalist",
        img: "/img/development/windlist.webp",
        type: "personal",
        location: "Personal",
        tags: ["react", "API", "tailwindCSS", "firebase"],
        live: "http://windlist.netlify.app",
        github: "https://github.com/takuyadev/windlist-firebase",
      },
      {
        title: "Sushi me!",
        img: "/img/development/sushime.webp",
        type: "education",
        location: "BCIT",
        tags: ["html", "css"],
        live: "https://takuyadev.github.io/sushime-styleguide/",
        github: "https://github.com/takuyadev/sushime-styleguide",
      },
      {
        title: "Salish Airways",
        img: "/img/design/salish_airways.webp",
        type: "education",
        location: "BCIT",
        tags: ["wordpress", "elementor"],
        live: "http://salishairway.altervista.org/",
      },
      {
        title: "Interview Scheduler",
        img: "/img/development/interviewer.webp",
        type: "education",
        location: "Lighthouse Labs",
        tags: ["react", "storybook", "cypress", "jest"],
        github: "https://github.com/takuyadev/interview-scheduler",
      },
      {
        title: "Tweeter",
        img: "/img/development/tweeter.webp",
        type: "education",
        location: "Lighthouse Labs",
        tags: ["jquery", "node.js", "express"],
        github: "https://github.com/takuyadev/tweeter",
      },
      {
        title: "Tiny App",
        img: "/img/development/tinyapp.webp",
        type: "education",
        location: "Ligthouse Labs",
        tags: ["jquery", "node.js", "express"],
        live: "https://tinyapp-0ryn.onrender.com/",
        github: "https://github.com/takuyadev/tinyapp",
      },
      {
        title: "Toyo Sushi",
        img: "/img/development/toyosushi.webp",
        type: "work",
        location: "Toyo Sushi",
        tags: ["wix", "photoshop"],
        live: "https://www.toyosushi.ca/",
      },
      {
        title: "Unit Converter",
        img: "/img/development/unit_converter.webp",
        type: "education",
        location: "Scrimba",
        tags: ["html", "css", "javascript ES6"],
        live: "https://takuyadev.github.io/unit-converter-scrimba/",
        github: "https://github.com/takuyadev/unit-converter-scrimba",
      },
      {
        title: "Dice Game",
        img: "/img/development/dice_game.webp",
        type: "education",
        location: "Scrimba",
        tags: ["html", "css", "javascript ES6"],
        live: "https://takuyadev.github.io/dice-game-scrimba/",
        github: "https://github.com/takuyadev/dice-game-scrimba",
      },
      {
        title: "Password Generator",
        img: "/img/development/password_gen.webp",
        type: "education",
        location: "Scrimba",
        tags: ["html", "css", "javascript ES6"],
        live: "https://takuyadev.github.io/password-generator-scrimba/",
        github: "https://github.com/takuyadev/password-generator-scrimba",
      },
      {
        title: "Invoice Generator",
        img: "/img/development/invoice_generator.webp",
        type: "education",
        location: "Scrimba",
        tags: ["html", "css", "javascript ES6"],
        live: "https://takuyadev.github.io/invoice-generator-scrimba/",
        github: "https://github.com/takuyadev/invoice-generator-scrimba",
      },
    ],
  });
}
